name: CI

on:
    push:
        branches: [ "**" ]
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Validate Gradle Wrapper
                uses: gradle/wrapper-validation-action@v2

            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    distribution: temurin
                    java-version: '21'
                    cache: gradle

            -   name: Gradle ktlint check
                run: ./gradlew --no-daemon ktlintCheck

            -   name: Run tests
                run: ./gradlew --no-daemon test

            -   name: Build (optional)
                run: ./gradlew --no-daemon build
